### ISSUE TITLE
SQSEventResponse with non-empty BatchItemFailures gets ignored

### ISSUE THREAD

**Issue by yerke** [aws/aws-lambda-go#430]
`SQSEventResponse` (that was introduced in https://github.com/aws/aws-lambda-go/pull/410 and is based on [`batchItemFailures`](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting)) does not work as expected. 

Specifically, the SQS messages do not end up being marked as failed, when you add the corresponding record ids to `BatchItemFailures` in `SQSEventResponse`.

My example code looks similar to the block below. I would expect all messages in a batch to fail in this example.
```
func HandleRequest(ctx context.Context, sqsEvent events.SQSEvent) (events.SQSEventResponse, error) {
	failedMessageIds := events.SQSEventResponse{}
	for _, message := range sqsEvent.Records {
		failedMessageIds.BatchItemFailures = append(failedMessageIds.BatchItemFailures, events.SQSBatchItemFailure{
			ItemIdentifier: message.MessageId,
		})
	}
	return failedMessageIds, nil
}
```

Returning error results in failing the whole batch. But `events.SQSEventResponse` seems to be ignored completely, and the batch is treated as successful every time. The expected behavior is that the messages with ids in `BatchItemFailures` should be be marked as failed, whereas the rest of the batch should marked as successfully processed.

Returning just `events.SQSEventResponse` instead of `(events.SQSEventResponse, error)` results in `handler returns a single value, but it does not implement error` error.

Part of my `go.mod`:
```
github.com/aws/aws-lambda-go v1.28.0
github.com/aws/aws-sdk-go v1.30.22
```

Am I doing something wrong?

@lyoung-confluent Does it work for you? Sorry to bother you, but you are most likely the most knowledgable person, since you [contributed](https://github.com/aws/aws-lambda-go/pull/410) it.

**Comment by yerke** [comment]
Turns out that terraform didn't apply `function_response_types = ["ReportBatchItemFailures"]` change. After I reran Terraform with that change and made sure that it's been picked up, I see the correct behavior.

![Screen Shot 2022-03-04 at 4 10 49 PM](https://user-images.githubusercontent.com/5137691/156858423-9109f578-5df7-4bb7-8d3a-91a4bc7d1e22.png)
